name: Build Pull Request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        continue-on-error: true
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        continue-on-error: true
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Debug Tests
        continue-on-error: true
        run: ./gradlew testDebugUnitTest

      - name: Run ktlint check
        continue-on-error: true
        run: ./gradlew ktlintCheck

      - name: Run Debug Lint
        continue-on-error: true
        run: ./gradlew lintDebug

      - name: Build with Gradle
        continue-on-error: true
        run: ./gradlew build

      - name: Upload Test Reports
        continue-on-error: true
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

      - name: Upload Ktlint Reports
        continue-on-error: true
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/ktlint/'

      - name: Upload Lint Reports
        continue-on-error: true
        if: ${{always()}}
          uses: actions/upload-artifact@v2
          with:
            name: test-reports
            path: '**/build/reports/lint-results/'

      - name: Upload APK
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
